"""Turn benchmark results into a JSON file and a Markdown summary table."""

from __future__ import annotations

import json
from pathlib import Path

from .models import BenchmarkResult


def save_json(results: list[BenchmarkResult], path: str | Path) -> Path:
    """Write all results to a pretty-printed JSON file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = [r.to_dict() for r in results]
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def to_markdown_table(results: list[BenchmarkResult]) -> str:
    """Render results as a GitHub-flavoured Markdown table.

    The table is the centrepiece of the README: it lets a reader compare
    latency and throughput across models at a glance.
    """
    header = (
        "| Model | Prompt | Category | Latency (s) | Tokens | Tokens/sec | Output preview |\n"
        "| --- | --- | --- | ---: | ---: | ---: | --- |"
    )
    rows = []
    for r in results:
        preview = r.error and f"ERROR: {r.error}" or r.response_preview
        # Escape pipes so they don't break the table layout.
        preview = preview.replace("|", "\\|")
        rows.append(
            f"| {r.model} | {r.prompt_name} | {r.category} | "
            f"{r.latency_seconds} | {r.total_tokens} | "
            f"{r.tokens_per_second} | {preview} |"
        )
    return "\n".join([header, *rows])


def save_markdown(results: list[BenchmarkResult], path: str | Path) -> Path:
    """Write a standalone Markdown report file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# Benchmark Results\n\n"
        "Generated by `open-models-playground`.\n\n"
        + to_markdown_table(results)
        + "\n"
    )
    path.write_text(body, encoding="utf-8")
    return path
